### ISSUE TITLE
Long call to SAL results in timeout and 500

### ISSUE THREAD

**Issue by robert-sanfeliu** [eu-nebulous/exn-middleware#8]
On PROD (r1 branch), using EXN middleware, Optimiser controller has to perform a syncRequest to SAL "deployCluster" endpoint using the eu.nebulouscloud.exn.sal.cluster.deploy topic.
This call can take up to 10 minutes to be completed by SAL if the requested cluster includes edge devices.

Apparently, there is some sort of timeout on EXN Middleware that cause such a call to fail. The timeout should be extended not to cause this error:

```
2024-12-06 08:39:21.055 ERROR 1 --- [pool-1-thread-7] e.n.e.m.s.p.impl.ClusterProcessor        : [admin -> create] Exception for null

org.springframework.web.client.ResourceAccessException: I/O error on POST request for "http://nebulous-sal:8080/sal/cluster/815c3-1": Read timed out; nested exception is java.net.SocketTimeoutException: Read timed out
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:791) ~[spring-web-5.3.31.jar!/:5.3.31]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:717) ~[spring-web-5.3.31.jar!/:5.3.31]
        at org.springframework.web.client.RestTemplate.postForEntity(RestTemplate.java:474) ~[spring-web-5.3.31.jar!/:5.3.31]
        at jdk.internal.reflect.GeneratedMethodAccessor16.invoke(Unknown Source) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
        at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:48) ~[groovy-3.0.19.jar!/:3.0.19]
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSite.invoke(PojoMetaMethodSite.java:186) ~[groovy-3.0.19.jar!/:3.0.19]
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:51) ~[groovy-3.0.19.jar!/:3.0.19]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:157) ~[groovy-3.0.19.jar!/:3.0.19]
        at eu.nebulouscloud.exn.modules.sal.repository.AbstractSalRepository.post(AbstractSalRepository.groovy:66) ~[classes!/:0.0.1-SNAPSHOT]
        at jdk.internal.reflect.GeneratedMethodAccessor24.invoke(Unknown Source) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
        at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:48) ~[groovy-3.0.19.jar!/:3.0.19]
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:189) ~[groovy-3.0.19.jar!/:3.0.19]
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:57) ~[groovy-3.0.19.jar!/:3.0.19]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51) ~[groovy-3.0.19.jar!/:3.0.19]
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:62) ~[groovy-3.0.19.jar!/:3.0.19]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:212) ~[groovy-3.0.19.jar!/:3.0.19]
        at eu.nebulouscloud.exn.modules.sal.repository.AbstractSalRepository.save(AbstractSalRepository.groovy:136) ~[classes!/:0.0.1-SNAPSHOT]
        at eu.nebulouscloud.exn.modules.sal.repository.AbstractSalRepository$save$0.callCurrent(Unknown Source) ~[na:na]
        at eu.nebulouscloud.exn.modules.sal.repository.cluster.ClusterRepository.postAction(ClusterRepository.groovy:22) ~[classes!/:0.0.1-SNAPSHOT]
        at eu.nebulouscloud.exn.modules.sal.repository.cluster.ClusterRepository$postAction.call(Unknown Source) ~[na:na]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) ~[groovy-3.0.19.jar!/:3.0.19]
        at eu.nebulouscloud.exn.modules.sal.repository.cluster.ClusterRepository$postAction.call(Unknown Source) ~[na:na]
        at eu.nebulouscloud.exn.modules.sal.processors.impl.ClusterProcessor.create(ClusterProcessor.groovy:56) ~[classes!/:0.0.1-SNAPSHOT]
        at eu.nebulouscloud.exn.modules.sal.processors.impl.ClusterProcessor$create.callCurrent(Unknown Source) ~[na:na]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51) ~[groovy-3.0.19.jar!/:3.0.19]
        at eu.nebulouscloud.exn.modules.sal.processors.impl.ClusterProcessor$create.callCurrent(Unknown Source) ~[na:na]
        at eu.nebulouscloud.exn.modules.sal.processors.AbstractProcessor.process(AbstractProcessor.groovy:62) ~[classes!/:0.0.1-SNAPSHOT]
        at eu.nebulouscloud.exn.modules.sal.processors.Processor$process.call(Unknown Source) ~[na:na]
        at eu.nebulouscloud.exn.modules.sal.middleware.handlers.consumer.AMQPSalMessageHandler.onMessage(AMQPSalMessageHandler.groovy:51) ~[classes!/:0.0.1-SNAPSHOT]
        at eu.nebulouscloud.exn.modules.sal.middleware.handlers.consumer.AMQPSalMessageHandler$onMessage.call(Unknown Source) ~[na:na]
        at eu.nebulouscloud.exn.core.Consumer.onDelivery(Consumer.groovy:77) ~[exn-connector-java-1.0-SNAPSHOT.jar!/:na]
        at jdk.internal.reflect.GeneratedMethodAccessor17.invoke(Unknown Source) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
        at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:48) ~[groovy-3.0.19.jar!/:3.0.19]
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:189) ~[groovy-3.0.19.jar!/:3.0.19]
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:69) ~[groovy-3.0.19.jar!/:3.0.19]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:148) ~[groovy-3.0.19.jar!/:3.0.19]
        at eu.nebulouscloud.exn.core.Manager$4.run(Manager.groovy:174) ~[exn-connector-java-1.0-SNAPSHOT.jar!/:na]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
        at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.base/java.net.SocketInputStream.socketRead0(Native Method) ~[na:na]
        at java.base/java.net.SocketInputStream.socketRead(Unknown Source) ~[na:na]
        at java.base/java.net.SocketInputStream.read(Unknown Source) ~[na:na]
        at java.base/java.net.SocketInputStream.read(Unknown Source) ~[na:na]
        at java.base/java.io.BufferedInputStream.fill(Unknown Source) ~[na:na]
        at java.base/java.io.BufferedInputStream.read1(Unknown Source) ~[na:na]
        at java.base/java.io.BufferedInputStream.read(Unknown Source) ~[na:na]
        at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(Unknown Source) ~[na:na]
        at java.base/sun.net.www.http.HttpClient.parseHTTP(Unknown Source) ~[na:na]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[na:na]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[na:na]
        at java.base/java.net.HttpURLConnection.getResponseCode(Unknown Source) ~[na:na]
        at org.springframework.http.client.SimpleClientHttpResponse.getRawStatusCode(SimpleClientHttpResponse.java:55) ~[spring-web-5.3.31.jar!/:5.3.31]
        at org.springframework.web.client.DefaultResponseErrorHandler.hasError(DefaultResponseErrorHandler.java:61) ~[spring-web-5.3.31.jar!/:5.3.31]
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:813) ~[spring-web-5.3.31.jar!/:5.3.31]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:783) ~[spring-web-5.3.31.jar!/:5.3.31]
        ... 47 common frames omitted

2024-12-06 08:39:21.056 ERROR 1 --- [pool-1-thread-7] e.n.e.m.s.p.impl.ClusterProcessor        : RAW EXCEPTION ERROR:
 I/O error on POST request for "http://nebulous-sal:8080/sal/cluster/815c3-1": Read timed out; nested exception is java.net.SocketTimeoutException: Read timed out

```

**Comment by gsavvas-exz** [comment]
This is solved here
https://github.com/eu-nebulous/exn-middleware/commit/6882046781344c1a5078b2a621c57681e249dad9
Merged in r1
